apiVersion: v1
kind: Service
metadata:
  name: my-backend-service
  labels:
    app: tripshare-api-spring
    tier: backend
#spec:
##  type: Cluster IP is a default service
#  selector:
#    app: tripshare-api-spring
#  ports:
#    - name: http
#      port: 8080 # ClusterIp Service Port
#      targetPort: 8080 # Container Port
spec:
  type: NodePort
  selector:
    app: tripshare-api-spring
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 31234
